"""empty message

Revision ID: 0eb3c84ec9ee
Revises: baf20662b591
Create Date: 2023-12-13 19:49:32.404093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0eb3c84ec9ee'
down_revision = 'baf20662b591'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('animation_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('schema_id', sa.Integer(), nullable=True))
        batch_op.alter_column('query',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_constraint('animation_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['userid'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('animation_ibfk_1', 'Users', ['user_id'], ['id'])
        batch_op.alter_column('query',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.drop_column('schema_id')
        batch_op.drop_column('animation_name')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

