"""empty message

Revision ID: 2ba603a6001f
Revises: fdf29526f7cb
Create Date: 2023-12-04 00:42:47.011863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ba603a6001f'
down_revision = 'fdf29526f7cb'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inv_ProductID', sa.Integer(), nullable=False))
        batch_op.drop_constraint('Inventory_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Product', ['inv_ProductID'], ['product_id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Inventory_ibfk_1', 'Product', ['product_id'], ['product_id'])
        batch_op.drop_column('inv_ProductID')

    # ### end Alembic commands ###

