"""empty message

Revision ID: 49efd1706251
Revises: 6708be958c07
Create Date: 2023-11-02 19:52:01.759496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49efd1706251'
down_revision = '6708be958c07'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('Persons')
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Persons',
    sa.Column('PersonID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('PersonID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('test')
    # ### end Alembic commands ###

