"""empty message

Revision ID: 6b218c2d9abe
Revises: 4b2028556fc8
Create Date: 2023-12-02 17:05:28.469510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b218c2d9abe'
down_revision = '4b2028556fc8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Passenger', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Passenger', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###

