"""empty message

Revision ID: 71d1778f8596
Revises: 4b8fe5a82bd1
Create Date: 2023-11-02 22:34:54.921685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d1778f8596'
down_revision = '4b8fe5a82bd1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz_QPA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz_QPA', schema=None) as batch_op:
        batch_op.drop_column('question_number')

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

