"""empty message

Revision ID: 7bb7869ea824
Revises: 71d1778f8596
Create Date: 2023-11-07 23:32:08.797655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb7869ea824'
down_revision = '71d1778f8596'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('account_type')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

