"""empty message

Revision ID: 7ddb261f9434
Revises: d9bf1cec5179
Create Date: 2023-12-13 14:34:15.203127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddb261f9434'
down_revision = 'd9bf1cec5179'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quiz_QuestionSet',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('quizID', sa.String(length=32), nullable=True),
    sa.Column('schema', sa.String(length=70), nullable=True),
    sa.Column('questionsID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['questionsID'], ['Quiz_QPA.qaid'], ),
    sa.ForeignKeyConstraint(['quizID'], ['Quiz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('Quiz_QPA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questionSetID', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'Quiz_QuestionSet', ['questionSetID'], ['id'])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz_QPA', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('questionSetID')

    op.drop_table('Quiz_QuestionSet')
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

