"""empty message

Revision ID: a87c1b6cf02d
Revises: f9a5feab0791
Create Date: 2023-12-06 21:48:09.487670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87c1b6cf02d'
down_revision = 'f9a5feab0791'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

