"""empty message

Revision ID: aa9bcf856f4b
Revises: b4d467dcbe39
Create Date: 2023-12-07 03:54:19.250218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa9bcf856f4b'
down_revision = 'b4d467dcbe39'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Filters',
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.String(length=32), nullable=True),
    sa.Column('matching_joins', sa.Boolean(), nullable=True),
    sa.Column('spell_check', sa.Boolean(), nullable=True),
    sa.Column('additional_data', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['Quiz.id'], ),
    sa.PrimaryKeyConstraint('filter_id'),
    sa.UniqueConstraint('filter_id')
    )
    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.drop_index('filter_id')

    op.drop_table('filters')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('filter_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filter_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('filter_desc', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('mark', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('filter_id')
    )
    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.create_index('filter_id', ['filter_id'], unique=False)

    op.drop_table('Filters')
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

