"""empty message

Revision ID: e47acf868957
Revises: 0eb3c84ec9ee
Create Date: 2023-12-13 19:54:03.114467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e47acf868957'
down_revision = '0eb3c84ec9ee'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animation', schema=None) as batch_op:
        batch_op.alter_column('ani_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animation', schema=None) as batch_op:
        batch_op.alter_column('ani_id',
               existing_type=sa.String(length=32),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

