"""empty message

Revision ID: e51a8cacabb0
Revises: aa9bcf856f4b
Create Date: 2023-12-07 03:58:19.116172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e51a8cacabb0'
down_revision = 'aa9bcf856f4b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Filters', schema=None) as batch_op:
        batch_op.alter_column('filter_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Filters', schema=None) as batch_op:
        batch_op.alter_column('filter_id',
               existing_type=sa.String(length=32),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

